name: build multi-arch series-scraper image

on:
  push:
    branches: main

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: login to ghcr
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: checkout lfs
        run: git lfs checkout
      - name: install buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: latest
      - name: build the image
        run: |
          docker buildx build --push \
            --tag docker.io/speedyconzales/series-scraper:latest \
            --tag ghcr.io/speedyconzales/series-scraper:latest \
            --platform linux/amd64,linux/arm64 .
      - name: Setup tmate session
        if: failure()
        timeout-minutes: 10
        uses: mxschmitt/action-tmate@v3
        with:
            limit-access-to-actor: true
